name: CD

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    uses: codeready-toolchain/devcluster/.github/workflows/test.yaml@master

  deploy:
    name: Deploy
    needs: test
    uses: codeready-toolchain/devcluster/.github/workflows/deploy.yaml@master
    secrets:
      quay_token: ${{ secrets.QUAY_TOKEN }}
      openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}